[package]
name = "serverless_wasm"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]
rand = "0.8.4"

[[bin]]
name = "serverless_wasm"
path = "src/main.rs"


[profile.release]
opt-level = 3
